sudo: required

language: node_js

node_js:
  - 6.1

services:
  - docker

before_script:
  - cd $TRAVIS_BUILD_DIR
  - cd src
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - npm install

after_success:
  - cd $TRAVIS_BUILD_DIR
  - docker build -t "davecss/result:latest" -t "davecss/result:1.0.$TRAVIS_BUILD_NUMBER" .

deploy:
  provider: script
  skip_cleanup: true
  script: docker push davecss/result
  on:
    branch: master
